version: '3.8'

services:
  # Blue-Green менеджер
  switchcraft:
    build: .
    ports:
      - "8080:8080"
    environment:
      - BLUE_PORT=5176
      - GREEN_PORT=5177
      - PROXY_PORT=8080
      - SERVICE_NAME=My Frontend App
    networks:
      - app-network

  # Blue среда (заглушка для теста)
  app-5176:
    image: nginx:alpine
    ports:
      - "5176:80"
    networks:
      - app-network
    volumes:
      - ./blue-health.html:/usr/share/nginx/html/health
      - ./blue-version.html:/usr/share/nginx/html/version

  # Green среда (заглушка для теста)
  app-5177:
    image: nginx:alpine
    ports:
      - "5177:80"
    networks:
      - app-network
    volumes:
      - ./green-health.html:/usr/share/nginx/html/health
      - ./green-version.html:/usr/share/nginx/html/version

networks:
  app-network:
